<?php

namespace Aym3ntn\MedecinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurRepository extends EntityRepository
{
    public function findMedecinBySecteur($user){
        $query = $this->_em->createQuery('
                SELECT s
                FROM MedecinBundle:Secteur s
                JOIN MedecinBundle:Medecin m
                WITH m.secteurs = s.id
                JOIN UserBundle:User u
                WITH u.secteurs = s.id
                where u.id = :id
                ')->setParameter('id',$user->getId());
        return $query->getOneOrNullResult();
    }

    public function findByUser($user){
        $query = $this->createQueryBuilder('s')->join('s.users','u','WITH','u.id = :id')->setParameter('id', $user);

        return $query->getQuery()->getResult();
    }

    public function findOneByUser($user){
        $query = $this->createQueryBuilder('s')->join('s.users','u','WITH','u.id = :id')->setParameter('id', $user);

        return $query->getQuery()->getOneOrNullResult();
    }

    public function getDelgSuperviseur($user){
        $superviseurs = $this->createQueryBuilder('q')
            ->select('u')
            ->from('UserBundle:User', 'u')
            ->where('u.roles LIKE :role')
            ->setParameter('role','%ROLE_SUPERVISEUR%')
            ->getQuery()->getResult();

        $secteur = $this->createQueryBuilder('s')
            ->join('s.users','u','WITH','u.id = :user')
            ->setParameter('user',$user)
            ->getQuery()
            ->getResult()[0];

        $superviseur = $this->createQueryBuilder('s')
            ->join('s.users','u','WITH','u.id IN (:superviseurs)')
            ->select('u.id')
            ->andWhere('s.id = :secteur')
            ->setParameter('secteur',$secteur->getId())
            ->setParameter('superviseurs',$superviseurs)
            ->getQuery()
            ->getSingleResult();

        $user = $this->getEntityManager()->getRepository('UserBundle:User')->find($superviseur);

        return $user;
    }
}
