<?php

namespace Aym3ntn\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function findByUser($user, $type){
        $query = $this->createQueryBuilder('n')
            ->groupBy('n.id')
            ->where('n.type = :type')
            ->setParameter('type', $type);

/*        $query1 = $this->createQueryBuilder('n')
            ->join('n.targets','t','WITH','t.id = :id')
            ->setParameter('id', $user)->getQuery()->getResult();

        $query = $this->createQueryBuilder('n')
            ->where(' n.type = :type ')
            ->andWhere(' n.id NOT IN (:targets) ')
            ->setParameters(array('targets' => $query1, 'type' => $type));*/

        return $query->getQuery()->getResult();
    }
}
