<?php

namespace Aym3ntn\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNoteRepository extends EntityRepository
{
    public function findByType(User $user, $type){

        $notes =  $this->createQueryBuilder('q')
            ->select('n')
            ->from('UserBundle:Note','n')
            ->where('n.user = :user')
            ->andWhere('n.type = :type')
            ->setParameters(array('user' => $user, 'type' => $type))->getQuery()->getResult();

        $query = $this->createQueryBuilder('q');
        $query->join('UserBundle:Note','n')
            ->where('n.type = :type')
            ->andWhere('q.user = :user')
            ->andWhere('q.note NOT IN (:notes)')
            ->setParameters(array('user' => $user, 'type' => $type, 'notes' => $notes));

        return $query->getQuery()->getResult();
    }
}
